engines:
  csslint:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD013:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript

ratings:
  paths:
  - "**.js"
  - "**.css"
  - "**.md"

exclude_paths:
- blog/
- bootstrap/
